version: '3'
services:
  politik-bei-uns-frontend-flask:
    container_name: politik-bei-uns-frontend-flask
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: ["python3", "runserver.py"]
    networks:
      shared_politik-bei-uns:
        aliases:
          - frontend-flask

  politik-bei-uns-frontend-worker:
    container_name: politik-bei-uns-frontend-worker
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - .:/app
    entrypoint: ["celery", "-A", "webapp.celery_entry_point", "worker"]
    networks:
      shared_politik-bei-uns:
        aliases:
          - frontend-worker

  politik-bei-uns-frontend-gulp:
    build:
      context: .
      dockerfile: Dockerfile.gulp
    container_name: politik-bei-uns-frontend-gulp
    volumes:
      - .:/app
      - politik_bei_uns_node_modules:/app/node_modules
    #entrypoint: ['sleep', '600000']
    entrypoint: ["gulp", 'watch']
    networks:
      shared_politik-bei-uns:
        aliases:
        - frontend-gulp

networks:
  shared_politik-bei-uns:
    external: true

volumes:
  politik_bei_uns_node_modules: